# Generated by Django 6.0.3 on 2026-03-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ride'),
        ),
    ]
