# Generated by Django 4.2.30 on 2026-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration_min',
            field=models.IntegerField(blank=True, help_text='Estimated drive time in minutes', null=True),
        ),
    ]
