# Generated by Django 4.2.30 on 2026-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route_coords',
            field=models.JSONField(blank=True, help_text='JSON array of [lon, lat] coordinates', null=True),
        ),
    ]
